language: php

php:
  - '5.5'
  - '5.6'

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
